#include "codegen.h"
#include <iostream>
#include <stdexcept>

// ── Helpers ────────────────────────────────────────────────────────────────

int CodeGen::emit(Instruction instr) {
    code.push_back(instr);
    return (int)code.size() - 1;
}

void CodeGen::patch(int idx, int target) {
    code[idx].operand = target;
}

// ── Top Level ──────────────────────────────────────────────────────────────

std::vector<Instruction> CodeGen::generate(ProgramNode& prog) {
    code.clear();
    for (auto& stmt : prog.stmts) emitStmt(stmt.get());
    emit(Instruction::simple(OpCode::HALT));
    return code;
}

// ── Statement Emitters ─────────────────────────────────────────────────────

void CodeGen::emitStmt(ASTNode* node) {
    if (auto* n = dynamic_cast<AssignNode*>(node)) {
        emitExpr(n->expr.get());
        emit(Instruction::store(n->name));
    }
    else if (auto* n = dynamic_cast<PrintNode*>(node)) {
        emitExpr(n->expr.get());
        emit(Instruction::simple(OpCode::PRINT));
    }
    else if (auto* n = dynamic_cast<IfNode*>(node)) {
        // Emit condition
        emitExpr(n->cond.get());
        int jmpFalseIdx = emit(Instruction::jmpFalse(-1)); // placeholder

        // Emit 'then' body
        for (auto& s : n->body) emitStmt(s.get());

        if (n->elseBody.empty()) {
            // Patch jump to after 'then'
            patch(jmpFalseIdx, (int)code.size());
        } else {
            // Jump over else at end of then
            int jmpOverElse = emit(Instruction::jmp(-1));
            patch(jmpFalseIdx, (int)code.size());
            for (auto& s : n->elseBody) emitStmt(s.get());
            patch(jmpOverElse, (int)code.size());
        }
    }
    else if (auto* n = dynamic_cast<WhileNode*>(node)) {
        int loopStart = (int)code.size();

        emitExpr(n->cond.get());
        int jmpFalseIdx = emit(Instruction::jmpFalse(-1)); // exit loop

        for (auto& s : n->body) emitStmt(s.get());
        emit(Instruction::jmp(loopStart));           // back-edge

        patch(jmpFalseIdx, (int)code.size());        // exit target
    }
    else {
        throw std::runtime_error("Unknown statement node in codegen");
    }
}

// ── Expression Emitters ────────────────────────────────────────────────────

void CodeGen::emitExpr(ASTNode* node) {
    if (auto* n = dynamic_cast<NumberNode*>(node)) {
        emit(Instruction::push(n->value));
    }
    else if (auto* n = dynamic_cast<IdentNode*>(node)) {
        emit(Instruction::load(n->name));
    }
    else if (auto* n = dynamic_cast<BinOpNode*>(node)) {
        emitExpr(n->left.get());
        emitExpr(n->right.get());
        switch (n->op) {
            case '+': emit(Instruction::simple(OpCode::ADD));    break;
            case '-': emit(Instruction::simple(OpCode::SUB));    break;
            case '*': emit(Instruction::simple(OpCode::MUL));    break;
            case '/': emit(Instruction::simple(OpCode::DIV));    break;
            case '<': emit(Instruction::simple(OpCode::CMP_LT)); break;
            case '>': emit(Instruction::simple(OpCode::CMP_GT)); break;
            case '=': emit(Instruction::simple(OpCode::CMP_EQ)); break;
            default:  throw std::runtime_error("Unknown binary operator");
        }
    }
    else {
        throw std::runtime_error("Unknown expression node in codegen");
    }
}

// ── Pretty-print Bytecode (the -emit-ir flag output) ──────────────────────

void CodeGen::printBytecode(const std::vector<Instruction>& code) const {
    std::cout << "\n╔══════════════════════════════════════╗\n";
    std::cout <<   "║         GENERATED BYTECODE           ║\n";
    std::cout <<   "╚══════════════════════════════════════╝\n";

    for (int i = 0; i < (int)code.size(); ++i) {
        const auto& instr = code[i];
        std::cout << "  [" << i << "]\t";

        switch (instr.op) {
            case OpCode::PUSH:
                std::cout << "PUSH    " << std::get<double>(instr.operand); break;
            case OpCode::LOAD:
                std::cout << "LOAD    " << std::get<std::string>(instr.operand); break;
            case OpCode::STORE:
                std::cout << "STORE   " << std::get<std::string>(instr.operand); break;
            case OpCode::ADD:    std::cout << "ADD";     break;
            case OpCode::SUB:    std::cout << "SUB";     break;
            case OpCode::MUL:    std::cout << "MUL";     break;
            case OpCode::DIV:    std::cout << "DIV";     break;
            case OpCode::CMP_LT: std::cout << "CMP_LT";  break;
            case OpCode::CMP_GT: std::cout << "CMP_GT";  break;
            case OpCode::CMP_EQ: std::cout << "CMP_EQ";  break;
            case OpCode::JMP:
                std::cout << "JMP     → [" << std::get<int>(instr.operand) << "]"; break;
            case OpCode::JMP_FALSE:
                std::cout << "JMP_F   → [" << std::get<int>(instr.operand) << "] (if false)"; break;
            case OpCode::PRINT:  std::cout << "PRINT";   break;
            case OpCode::HALT:   std::cout << "HALT";    break;
        }
        std::cout << "\n";
    }
    std::cout << "\n";
}